import React from 'react';

export default function Loading() {
    return (
        <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 100 100"
            preserveAspectRatio="xMidYMid"
            width="100"
            height="100"
            style={{ shapeRendering: 'auto', display: 'block', background: 'rgba(255, 255, 255, 0)' }}
            xmlnsXlink="http://www.w3.org/1999/xlink"
        >
            <g>
                <rect fill="#000000" height="20" width="20" y="19" x="19">
                    <animate
                        calcMode="discrete"
                        begin="0s"
                        repeatCount="indefinite"
                        dur="1s"
                        keyTimes="0;0.125;1"
                        values="#6b6a6a;#000000;#000000"
                        attributeName="fill"
                    />
                </rect>
                <rect fill="#000000" height="20" width="20" y="19" x="40">
                    <animate
                        calcMode="discrete"
                        begin="0.125s"
                        repeatCount="indefinite"
                        dur="1s"
                        keyTimes="0;0.125;1"
                        values="#6b6a6a;#000000;#000000"
                        attributeName="fill"
                    />
                </rect>
                <rect fill="#000000" height="20" width="20" y="19" x="61">
                    <animate
                        calcMode="discrete"
                        begin="0.25s"
                        repeatCount="indefinite"
                        dur="1s"
                        keyTimes="0;0.125;1"
                        values="#6b6a6a;#000000;#000000"
                        attributeName="fill"
                    />
                </rect>
                <rect fill="#000000" height="20" width="20" y="40" x="19">
                    <animate
                        calcMode="discrete"
                        begin="0.875s"
                        repeatCount="indefinite"
                        dur="1s"
                        keyTimes="0;0.125;1"
                        values="#6b6a6a;#000000;#000000"
                        attributeName="fill"
                    />
                </rect>
                <rect fill="#000000" height="20" width="20" y="40" x="61">
                    <animate
                        calcMode="discrete"
                        begin="0.375s"
                        repeatCount="indefinite"
                        dur="1s"
                        keyTimes="0;0.125;1"
                        values="#6b6a6a;#000000;#000000"
                        attributeName="fill"
                    />
                </rect>
                <rect fill="#000000" height="20" width="20" y="61" x="19">
                    <animate
                        calcMode="discrete"
                        begin="0.75s"
                        repeatCount="indefinite"
                        dur="1s"
                        keyTimes="0;0.125;1"
                        values="#6b6a6a;#000000;#000000"
                        attributeName="fill"
                    />
                </rect>
                <rect fill="#000000" height="20" width="20" y="61" x="40">
                    <animate
                        calcMode="discrete"
                        begin="0.625s"
                        repeatCount="indefinite"
                        dur="1s"
                        keyTimes="0;0.125;1"
                        values="#6b6a6a;#000000;#000000"
                        attributeName="fill"
                    />
                </rect>
                <rect fill="#000000" height="20" width="20" y="61" x="61">
                    <animate
                        calcMode="discrete"
                        begin="0.5s"
                        repeatCount="indefinite"
                        dur="1s"
                        keyTimes="0;0.125;1"
                        values="#6b6a6a;#000000;#000000"
                        attributeName="fill"
                    />
                </rect>
            </g>
            {/* [ldio] generated by https://loading.io */}
        </svg>
    );
}